version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_ACCOUNT_URL
          repo: '${MY_APP_PREFIX}'
          tag: "'latest,${CIRCLE_SHA1}"